name = input();
print("LENGTH OF THE STRING IS ", len(name));
print(name[:4]);
print(name.upper());
print(name.lower());
print(name.strip());
#print(name.rstrip("japati"));
print(name.replace("Lalit", "Vijesh"));
print(name.split(","));
print(name.capitalize());
print(name.center(50));
print(name.count('a'));
print(name.endswith("Prajapati"));
print(name.find("Praja"));
print(name.index("Lalit"));
print(name.isalnum());
print(name.isspace());
print(name.istitle());
print(name.startswith("Lalit"));
print(name.swapcase());